import type { Map as MapLibreMap } from 'maplibre-gl'

const ICON_IDS = ['public', 'mall', 'konbini', 'purchase'] as const
export type IconId = (typeof ICON_IDS)[number]

// 128px to match the 4x-rasterized SVG (width/height = 4 × viewBox).
// pixelRatio: 4 below tells MapLibre this is a 4x-density source;
// combined with the layer's icon-size: 1 the icon is 32px logical.
// On Retina (DPR 2) the 64px physical target is downsampled from 128px
// — the downsample is what produces sharp edges, vs the 2x source that
// was effectively 1:1 and still showed pixelation.
const ICON_SIZE = 128

/**
 * Load the four toilet-type SVGs into the MapLibre image registry as
 * `toilet-${id}`. Call once after the Map's 'load' event fires.
 *
 * SVGs come from public/toilet-icons/ (generated by the T3.3 script).
 * We fetch as text → wrap in a Blob → URL.createObjectURL → <Image> →
 * map.addImage. pixelRatio 2 lets MapLibre render the 32×32 source at
 * Retina sharpness without manual 64×64 PNG generation.
 *
 * Idempotent at the per-icon level via map.hasImage(); safe to call
 * again (e.g. after a hot reload) without leaking image registrations.
 */
export async function loadToiletIcons(map: MapLibreMap): Promise<void> {
  await Promise.all(
    ICON_IDS.map(async (id) => {
      const imageId = `toilet-${id}`
      if (map.hasImage(imageId)) return

      const res = await fetch(`/toilet-icons/${id}.svg`)
      if (!res.ok) throw new Error(`Failed to fetch icon ${id}: ${res.status}`)

      const svgText = await res.text()
      const blob = new Blob([svgText], { type: 'image/svg+xml' })
      const url = URL.createObjectURL(blob)

      await new Promise<void>((resolve, reject) => {
        const img = new Image(ICON_SIZE, ICON_SIZE)
        img.onload = () => {
          map.addImage(imageId, img, { pixelRatio: 4 })
          URL.revokeObjectURL(url)
          resolve()
        }
        img.onerror = () => {
          URL.revokeObjectURL(url)
          reject(new Error(`Image load failed for ${id}`))
        }
        img.src = url
      })
    }),
  )
}

/** Map Prisma ToiletType enum value to the icon id used by addImage. */
export function typeToIconId(type: string): IconId {
  switch (type) {
    case 'PUBLIC':
      return 'public'
    case 'MALL':
      return 'mall'
    case 'KONBINI':
      return 'konbini'
    case 'PURCHASE':
      return 'purchase'
    default:
      return 'public'
  }
}
